// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5mEcBYfcRTSCRq091mStyFXgfGUG42Jc',
    appId: '1:327158144901:web:9a39d694fb2d7af1e96eec',
    messagingSenderId: '327158144901',
    projectId: 'nutricare-986e8',
    authDomain: 'nutricare-986e8.firebaseapp.com',
    storageBucket: 'nutricare-986e8.firebasestorage.app',
    measurementId: 'G-7C23K9SCVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4DLETCidXTiuDpKg4qZyZebXzOlclgo',
    appId: '1:327158144901:android:e2db82a38c160efbe96eec',
    messagingSenderId: '327158144901',
    projectId: 'nutricare-986e8',
    storageBucket: 'nutricare-986e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYT9D3eyD1sUPycxHxu6BDbYelInx0Yb4',
    appId: '1:327158144901:ios:5c2bc545af4a07c3e96eec',
    messagingSenderId: '327158144901',
    projectId: 'nutricare-986e8',
    storageBucket: 'nutricare-986e8.firebasestorage.app',
    iosBundleId: 'com.example.nutriCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYT9D3eyD1sUPycxHxu6BDbYelInx0Yb4',
    appId: '1:327158144901:ios:5c2bc545af4a07c3e96eec',
    messagingSenderId: '327158144901',
    projectId: 'nutricare-986e8',
    storageBucket: 'nutricare-986e8.firebasestorage.app',
    iosBundleId: 'com.example.nutriCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5mEcBYfcRTSCRq091mStyFXgfGUG42Jc',
    appId: '1:327158144901:web:5500fce257c4992de96eec',
    messagingSenderId: '327158144901',
    projectId: 'nutricare-986e8',
    authDomain: 'nutricare-986e8.firebaseapp.com',
    storageBucket: 'nutricare-986e8.firebasestorage.app',
    measurementId: 'G-3EE0J9JPDC',
  );
}
